### ISSUE TITLE
Cant find youtube video

### ISSUE THREAD

**Issue by KatzeMau** [s77rt/YouTubeDownloader#2]
When i paste an link into the program, i get error 404 from "GetVideo"

<img width="602" alt="Bildschirmfoto 2021-05-25 um 12 46 58" src="https://user-images.githubusercontent.com/46974624/119485408-52917180-bd57-11eb-98dc-dbb0b467fd08.png">

**Comment by s77rt** [comment]
This should be fixed, please try the latest release:
https://github.com/s77rt/YouTubeDownloader/releases/latest

**Comment by KatzeMau** [comment]
Fixed it
